#!/bin/bash
for seq in "hifi" "ont";
do
    for ver in v207 v22 v23;
    do 
        vcf="mendelian_${seq}/trio_${ver}.vcf.gz"
        [[ ! -d "mendelian_${seq}/results" ]] && mkdir mendelian_${seq}/results
        echo "# ${seq}|${ver} => ${vcf}";
        echo "## Original"
        bcftools +mendelian2 --pfm 1X:hg002,hg003,hg004 --mode c ${vcf} |  grep "^n"
        bcftools +mendelian2 --pfm 1X:hg002,hg003,hg004 --mode e ${vcf} | nutty pop --only-gt | \
            grep -v "#" | cut -f 6,8,9,10 |  sort | uniq -c | sort -k 1 > mendelian_${seq}/results/trio_${ver}_OG_gt_supp.txt
        bcftools  ${vcf} | nutty sv --info-tag SUPP_VEC | \
            cut -f 3 | sort | uniq -c > mendelian_${seq}/results/trio_${ver}_OG_supp.txt
        echo "## SUPP_VEC + GT fixed"
        zcat ${vcf} | nutty pop --fix-suppvec --fix-gt --output-vcf | \
            bcftools +mendelian2 --pfm 1X:hg002,hg003,hg004 --mode c - |  grep "^n"
        zcat ${vcf} | nutty pop --fix-suppvec --fix-gt --output-vcf | \
            bcftools +mendelian2 --pfm 1X:hg002,hg003,hg004 --mode e - | nutty pop --only-gt | \
            grep -v "#" | cut -f 6,8,9,10 |  sort | uniq -c | sort -k 1 > mendelian_${seq}/results/trio_${ver}_FX_gt_supp.txt
        zcat ${vcf} | nutty pop --fix-suppvec --fix-gt --output-vcf | \
            bcftools +mendelian2 --pfm 1X:hg002,hg003,hg004 --mode e - | nutty sv --info-tag SUPP_VEC | \
            cut -f 3 | sort | uniq -c > mendelian_${seq}/results/trio_${ver}_FX_supp.txt
    done
done

# REGEX: # (.*)\|(.*) => .*\n## (.*)\nngood\t(\d+)\nnmerr\t(\d+)\nnmissing\t(\d+)\n## SUPP_VEC \+ GT fixed\nngood\t(\d+)\nnmerr\t(\d+)\nnmissing\t(\d+)\n
#        $1|$3\n$2\t$4\t$5\t$6\n$1|FIX\n$2\t$7\t$8\t$9\n